### ISSUE TITLE
Virtual Camera Source

### ISSUE THREAD

**Issue by dtynski** [lukehsiao/CribSense#55]
I'm running a virtual camera source instead of the camera in your tutorial.  When I specify that camera (which I can view via VLC so I know the virtual device is working), I get a "invalid argument error from Cribsense. Any idea how to troubleshoot?

**Comment by gcampax** [comment]
Try running it in strace (strace -e trace=ioctl cribsense) to see what IOCTL is failing. It's likely that we're passing some parameter value (eg picture format) that is valid for the Pi driver but not for your camera.
