### ISSUE TITLE
Viewing the video stream

### ISSUE THREAD

**Issue by tomforsyth90** [lukehsiao/CribSense#56]
This is exactly what I was looking to implement into my baby monitor. I've got it working so it is currently streaming the video via gstreamer but wanted to know if there was a way to use this also to monitor movement and breathing? If I download CribSense on a new sd card it runs fine but if I run it on the sd card i'm using for my baby monitor video stream it doesn't work and fails after starting the batch processing.. any suggestions how I can get this to work? Also is there a way to visualise the pixel movement and motion estimate to reflect breathing rate? Thanks

**Comment by lukehsiao** [comment]
>If I download CribSense on a new sd card it runs fine but if I run it on the sd card i'm using for my baby monitor video stream it doesn't work and fails after starting the batch processing.. any suggestions how I can get this to work?

This one would be hard to debug without a lot of details. I'm not sure what might be causing this.

>Also is there a way to visualise the pixel movement and motion estimate to reflect breathing rate?

It is possible to show the diff frames similar to the one you see during configuration
![diff-frame](https://lukehsiao.github.io/CribSense/img/motion.png)

but in our implementation, rendering these added too much overhead and the Pi couldn't keep up. Adding any other visual indicators would have to be very lightweight. We do have some estimates of the motion that we can output to the terminal as shown [on the configuration page](https://lukehsiao.github.io/CribSense/setup/config/), if that's helpful. I've copied it here for convenience:

```
[info] Pixel Movement: 0     [info] Motion Estimate: 1.219812 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 1.219812 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 1.219812 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 1.219812 Hz
[info] Pixel Movement: 44    [info] Motion Estimate: 1.219812 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 1.219812 Hz
[info] Pixel Movement: 161   [info] Motion Estimate: 1.219812 Hz
[info] Pixel Movement: 121   [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 86    [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 97    [info] Motion Estimate: 0.841416 Hz
[info] Pixel Movement: 74    [info] Motion Estimate: 0.839298 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.839298 Hz
[info] Pixel Movement: 60    [info] Motion Estimate: 0.839298 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.839298 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.839298 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.839298 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.839298 Hz
[info] Pixel Movement: 48    [info] Motion Estimate: 0.839298 Hz
[info] Pixel Movement: 38    [info] Motion Estimate: 0.839298 Hz
[info] Pixel Movement: 29    [info] Motion Estimate: 0.839298 Hz
[info] Pixel Movement: 28    [info] Motion Estimate: 0.839298 Hz
[info] Pixel Movement: 22    [info] Motion Estimate: 0.839298 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.839298 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.839298 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.839298 Hz
[info] Pixel Movement: 0     [info] Motion Estimate: 0.839298 Hz
```

We have no plans on adding any other visualizations at this time, but pull requests are always welcome.

**Comment by tomforsyth90** [comment]
Ah okay, well is it possible for the rpi camera to be used for two tasks simultaneously? I assume that might be the issue? Is it possible to change your sound alerts when no motion is found to instead of setting off the speaker to send a push notification etc? I was planning on not using a speaker but if motion wasn't detected it would alert my mobile phone instead...

**Comment by lukehsiao** [comment]
>Ah okay, well is it possible for the rpi camera to be used for two tasks simultaneously?

This one I'm not sure about. We are _heavily_ utilizing the resources on the Pi, so I suspect trying to do any other computationally heavy task on the Pi will not work out well.

>Is it possible to change your sound alerts when no motion is found to instead of setting off the speaker to send a push notification etc? I was planning on not using a speaker but if motion wasn't detected it would alert my mobile phone instead...

You should be able to implement that, yes. We just have a simple [placeholder function here](https://github.com/lukehsiao/CribSense/blob/2674eec474acb4576536e4058db2e93405e903da/src/MotionDetection.cpp#L113-L121) that plays the sound. You could definitely implement a push notification instead.

**Comment by gcampax** [comment]
You cannot open the same video device from two processes at the same time, so you cannot have two processes streaming from the camera.
You could copy the data around, but keep in mind at the current resolution even just a copy can have noticeable performance impact.

**Comment by tomforsyth90** [comment]
@gcampax what about using something like v4l2loopback which "allows you to create "virtual video devices" normal (v4l2) applications will read these devices as if they were ordinary video devices, but the video will not be read from e.g. a capture card but instead it is generated by another application. this allows you for instance to apply apply some nifty video effects on your Skype video... it also allows some more serious things" Would using this make it possible?

**Comment by gcampax** [comment]
I'm not familiar with v4l2loopback, but from the description it appears it would work.
At the same time, again you might want to consider the overhead of copying the data around, or whether v4l2loopback and the process actually reading from the camera can support zero-copy sharing using dma-bufs. Assuming the raspberry pi camera driver supports dma-buf, which might depend on the kernel version.
Another all-in-one solution for multiple process access to the camera is https://github.com/PipeWire/pipewire (formerly pithos formerly pulsevideo), but again that depends on dma-buf and might have overhead. At the same time, dma-buf will give you zero-copy sharing with the output graphic card as well, so you might get pass through video overlay with small overhead, assuming you insist hard enough in your userspace.

**Comment by tomforsyth90** [comment]
Right okay thanks for the link and insight.. What about using a webcam instead of the rpi camera? Next question ha.. the estimates of motion you see in the command terminal, how would I go about embedding that into a webpage so you could view the real time detected motion or is that not possible and I should just let it run in the back ground?

**Comment by tomforsyth90** [comment]
@gcampax thanks for getting back to me. I've had a look at v4l2loopback but it says i need to have specific kernel headers installed but doesn't explain how to ensure you have the right ones installed and the pipewire alternative i cant figure out how to install without sudo-apt get lol :( could you walk me through it please otherwise i'm going to have to buy a second pi and camera and run cribsense completely separately which would be annoying.

**Comment by gcampax** [comment]
I'm afraid I can't help you, I am not familiar with these projects, I just know they exist.
At least pipewire should be installable from sources using a standard build system, as described in their README.

**Comment by tomforsyth90** [comment]
That's okay, thanks. Do you think Cribsense will be able to run on a raspberry pi zero? Think i'm going to have to run it on a separate pi now to be honest.

**Comment by lukehsiao** [comment]
Right now, yes. It's setup to turn on, look for motion, and then begin monitoring. If there is no baby and no motion, then the alarm would sound.

**Comment by tomforsyth90** [comment]
That's okay i'll ensure that is the case in my project then, cheers
