### ISSUE TITLE
How to play an mp3 as the alarm?

### ISSUE THREAD

**Issue by tomforsyth90** [lukehsiao/CribSense#57]
Hi 

Just wondering how I can change the code so I can play an mp3 file when the system alarms?
Also, I'm wondering if could tell me how I could make a specific gpio pin go high when the alarm is triggered and stay low/ return to low the rest of the time?

Cheers guys, will really appreciate it

**Comment by lukehsiao** [comment]
We play the alarm in [this file](https://github.com/lukehsiao/CribSense/blob/b67ae6a18a34dfdd900ef8728e4309a9aa780e81/src/MotionDetection.cpp#L113-L121).

You can modify that however you would like to play different sounds, or control [GPIO pins](https://www.raspberrypi.org/documentation/usage/gpio-plus-and-raspi2/README.md). We don't actually use any GPIO in this project, besides as a power source for the LED. So, I'd recommend checking out other online tutorials for how to set up GPIO using C++ on the Raspberry Pi.

**Comment by tomforsyth90** [comment]
Sorry I'm not very experienced with C. What exactly in that file would need changing to make it play an mp3 file?
Thanks

On 12 Mar 2018 05:49, Luke Hsiao <notifications@github.com> wrote:

We play the alarm in this file<https://github.com/lukehsiao/CribSense/blob/b67ae6a18a34dfdd900ef8728e4309a9aa780e81/src/MotionDetection.cpp#L113-L121>.

You can modify that however you would like to play different sounds, or control GPIO pins<https://www.raspberrypi.org/documentation/usage/gpio-plus-and-raspi2/README.md>. We don't actually use any GPIO in this project, besides as a power source for the LED. So, I'd recommend checking out other online tutorials for how to set up GPIO using C++ on the Raspberry Pi.

**Comment by tomforsyth90** [comment]
@lukehsiao Hi Luke, I can't get the alarm to work, my speakers are working fine as I can play other stuff through them via the Pi.. any ideas what I can do? Or how I can change the current alarm to something else? Thanks!

**Comment by lukehsiao** [comment]
I'd check out the other troubleshooting tips first: https://lukehsiao.github.io/CribSense/setup/troubleshooting/

**Comment by tomforsyth90** [comment]
Gone through all of that.. its definitely using the audio jack but not playing an alarm when i run` cribsense --config /etc/cribsense/config.ini`

**Comment by lukehsiao** [comment]
Is it detecting motion? Have you calibrated?

**Comment by tomforsyth90** [comment]
It detects motion and when no motion is detected during testing it prints error no motion is detected and then resets after a little while and runs through it all again... it's just not alarming.. i've tried changing the printf file to see if its updating changes but that won't print anything other than the original 'error no motion is detected' text

**Comment by lukehsiao** [comment]
Have you installed all dependencies (e.g. libcanberra-dev)?

**Comment by tomforsyth90** [comment]
yeah just double checked and they're all installed and updated

**Comment by lukehsiao** [comment]
Hmmm, I'm not sure then. If you find the cause, please follow-up here so others in the future can benefit from your debugging.

**Comment by tomforsyth90** [comment]
![cribsense](https://user-images.githubusercontent.com/34650406/38768506-ed9f7794-3fec-11e8-8747-decb733d80f1.jpg)
![cribsense2](https://user-images.githubusercontent.com/34650406/38768507-edba7db4-3fec-11e8-87c6-06eea0d19b65.jpg)

This is what happens when i enable cribesense and did the journal to check if its running.. not sure if its actually enabling properly?

Still can't get the alarm to sound, but even if i change the text in this section it still prints the original error no movement detected message.... any ideas?

Thanks

Tom

**Comment by tomforsyth90** [comment]
Do I need to change anything in any other file to allow editing to occur?

**Comment by lukehsiao** [comment]
Are you [rebuilding the project](https://lukehsiao.github.io/CribSense/setup/sw-setup/#build) after your edits?

**Comment by tomforsyth90** [comment]
No.. do i need to rerun this code again after each edit then?
`./autogen.sh --prefix=/usr --sysconfdir=/etc --disable-debug
make
sudo make install
sudo systemctl daemon-reload`

**Comment by lukehsiao** [comment]
I believe you can just 
```
$ make
$ sudo make install
$ sudo systemctl daemon-reload
```
Give that a shot. Right now you've edited the code, but are just running the old executables.

**Comment by tomforsyth90** [comment]
LOL i've spent weeks trying to make changes to that file and all i needed to do was that!! Thankyou!!!! Undoubtedly I will have another question for you when i get stuck again... thanks though Luke!!

**Comment by tomforsyth90** [comment]
I still cant get the alarm to play through the speakers, but I can play other mp3 files through them so not sure why its not doing it. What would I need to replace within this code to get it play an mp3 file: home/pi/music/alarm.mp3 and play that until motion is detected again and how should it be written?
```cpp
void MotionDetection::soundAlarm() {
    int playing;
    ca_context_playing(snd_context, 0, &playing);
    if (playing == 0)
        ca_context_play(snd_context, 0, CA_PROP_EVENT_ID, "alarm-clock-elapsed", nullptr);
    printf("[ERROR] >>>>> NO MOVEMENT DETECTED!!!!!!\n\n");
```

cheers Luke :)

**Comment by tomforsyth90** [comment]
I've put printf('test'); before int playing; and after it and that gets displayed in the command terminal so its obviously calling the script properly... does there need to be some sort of audio file that the alarm plays? how or what is it using to play an alarm at the moment? i've done a fresh install but it's still not playing an alarm.. hmm

**Comment by tomforsyth90** [comment]
Just to let you know that I have found a work around which can be used if anyone else is have issue with the alarm playing.. add the following
```cpp
#include <stdlib.h>
```
and replace soundAlarm() with:
```cpp
void MotionDetection::soundAlarm() {
  printf("[ERROR] >>>>> NO MOVEMENT DETECTED!!!!!!\n\n");
  system("omxplayer /home/pi/Music/AnySoundOrSongYouWish.mp3");
```
:)

**Comment by lukehsiao** [comment]
We use `libcanberra` to play the alarm. I'm not sure exactly what the issue you had was, but it appears that libcanberra wasn't able to find the `alarm-clock-elapsed` audio. Your workaround is one way to do it (calling an external program), but you can also look for other libraries that can play mp3 directly in C++.
