### ISSUE TITLE
Remove unused dependencies.

### ISSUE THREAD

**Issue by gcampax** [lukehsiao/CribSense#7]
For sure, we shouldn't need qt5webkit, for example.
And if opencv needs gtk, it should be pulled as a dep, not installed explicitly.

**Comment by lukehsiao** [comment]
Going to put a fresh install of linux on the remote raspberry pi and bring up the software with as few dependencies as possible.

**Comment by lukehsiao** [comment]
Confirmed that the setup in the new doc pages works on a fresh install of Raspbian.
